header:
  logo: /logos.png

  menu:
    - title: Home
      url: /
    - title: Services
      url: /services/
    - title: Giveaway
      url: /giveaway/
    - title: Contact
      url: /contact/

  button:
    text: Book a Shine
    url: /book/


footer:
  about: >
    We Come Shine is Portland's trusted mobile auto detailing service. 
    We bring premium interior and exterior car cleaning right to your driveway.

  menu:
    - title: Home
      url: /
    - title: Services
      url: /services/
    - title: About
      url: /about/
    - title: Contact
      url: /contact/

  social:
    facebook: "https://www.facebook.com/WeComeShine"
    instagram: "https://www.instagram.com/WeComeShine"
    pinterest: "https://www.pinterest.com/WeComeShine"

  logo: /logos.png
  copyright: "© 2025 We Come Shine. All rights reserved."
