title: We Come Shine
description: Portland’s mobile auto detailing service
url: "https://wecomeshine.com"
baseurl: 

theme: minima

google_analytics: G-XXXXXXXXXX # Replace with your actual tracking ID

# Optional SEO/social settings
Founder: Rodrigue Ban 
email: wecomeshine@gmail.com
